project_title: HSK-pop
project_tagline: selected K-pop jewels, brought to you by kevinsayhi
owner_name: kevinsayhi
owner_url: https://github.com/popksh
owner_email: popksh@gmail.com
asset_path_prefix: /
